///|
using @protobuf {type FieldDescriptorProto_Type}

///|
using @model {
  type Enum,
  type Field,
  type FieldCodecCardinality,
  type FieldCodecPresence,
  type FieldCodecShape,
  type FieldCodecValue,
  type FieldJsonCardinality,
  type FieldJsonShape,
  type FieldStorageShape,
  type ImportPath,
  type Message,
  type MessageShape,
  type OneOf,
  type OneofFieldShape,
  type OneofShape,
  type Package,
}
