///|
using @protobuf {type FieldDescriptorProto_Type}

///|
using @model {
  type Enum,
  type Field,
  type FieldCodecCardinality,
  type FieldCodecPresence,
  type FieldCodecReadMode,
  type FieldCodecShape,
  type FieldCodecValue,
  type FieldEnvelopeShape,
  type FieldJsonCardinality,
  type FieldJsonShape,
  type FieldStorageShape,
  type ImportPath,
  type Message,
  type MessageShape,
  type Method,
  type OneOf,
  type OneofFieldShape,
  type OneofShape,
  type Package,
  type Service,
  type ServiceMethodShape,
  type ServiceShape,
}
