pub(all) struct User {
  mut user_id : String
  mut name : String
  mut email : String?
  mut orders : Array[Order]
  mut friends : Array[User]
} derive(Eq, Show)
pub impl @protobuf.Sized for User with size_of(self) {
  let mut size = 0U
  size += 1U + { let size = @protobuf.size_of(self.user_id); @protobuf.size_of(size) + size }
  size += 1U + { let size = @protobuf.size_of(self.name); @protobuf.size_of(size) + size }
  match self.email {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size += self.orders.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size += self.friends.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size
}
pub impl Default for User with default() -> User {
  User::{
    user_id : String::default(),
    name : String::default(),
    email : None,
    orders : [],
    friends : [],
  }
}
pub async fn[R: @protobuf.AsyncReader] User::read(reader : R) -> User raise {
  let reader = @protobuf.LimitedReader::new(reader)
  User::read_with_limit(reader)
}
pub async fn[R: @protobuf.AsyncReader] User::read_with_limit(reader : @protobuf.LimitedReader[R], limit ?: Int) -> User raise {
  let new_limit = if reader.limit is Some(l) && limit is Some(limit) {
    if l < limit { raise @protobuf.EndOfStream }
    Some(l - limit)
  } else { None }
  reader.limit = limit
  let msg = User::default()
  try {
    for {
      match (reader |> @protobuf.async_read_tag()) {
      (1, _) => msg.user_id = reader |> @protobuf.async_read_string()
      (2, _) => msg.name = reader |> @protobuf.async_read_string()
      (3, _) => msg.email = reader |> @protobuf.async_read_string() |> Some
      (4, _) => msg.orders.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Order::default()
    } else {
      Order::read_with_limit(reader, limit=len)
    }
  })
      (5, _) => msg.friends.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      User::default()
    } else {
      User::read_with_limit(reader, limit=len)
    }
  })
       (_, wire) => reader |> @protobuf.async_read_unknown(wire)
      }
    }
  } catch {
    @protobuf.EndOfStream => ()
    err => raise err
  }
  reader.limit = new_limit
  msg
}
pub async fn[W: @protobuf.AsyncWriter] User::write(self:Self, writer : W) -> Unit raise {
  writer |> @protobuf.async_write_varint(10UL);writer |> @protobuf.async_write_string(self.user_id)
  writer |> @protobuf.async_write_varint(18UL);writer |> @protobuf.async_write_string(self.name)
  match self.email {
    Some(v) => {
      writer |> @protobuf.async_write_varint(26UL);writer |> @protobuf.async_write_string(v)
    }
    None => ()
  }
  for i in 0..<self.orders.length() {
        writer |> @protobuf.async_write_varint(34UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.orders[i])); self.orders[i].write(writer)
  }
  for i in 0..<self.friends.length() {
        writer |> @protobuf.async_write_varint(42UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.friends[i])); self.friends[i].write(writer)
  }
}
pub impl ToJson for User with to_json(self) {

  let json: Map[String, Json] = {}
  if self.user_id != Default::default() {
  json["userId"] = self.user_id.to_json()
  }
  if self.name != Default::default() {
  json["name"] = self.name.to_json()
  }
  match self.email {
      Some(v) => json["email"] = v.to_json()
      _ => ()
    }
  if self.orders != Default::default() {
  json["orders"] = self.orders.to_json()
  }
  if self.friends != Default::default() {
  json["friends"] = self.friends.to_json()
  }
  Json::object(json)
}
pub impl @json.FromJson for User with from_json(json: Json, path: @json.JsonPath) -> User raise {
  guard json is Object(obj) else {
    raise @json.JsonDecodeError((path, "Expected an object for User"))
  }
  let message = User::default()

  for key, value in obj {
    match (key, value) {
      ("userId", value) => message.user_id = @json.from_json(value, path~)
      ("name", value) => message.name = @json.from_json(value, path~)
      ("email", value) => message.email = Some(@json.from_json(value, path~))
      ("orders", Array(value)) => message.orders = value.map(v => 
@json.from_json(v, path~))
      ("friends", Array(value)) => message.friends = value.map(v => 
@json.from_json(v, path~))
      key => raise @json.JsonDecodeError((path, "Unknown field \{key}"))
      }
  }
  message
}
pub(all) struct Order {
  mut order_id : String
  mut product_name : String
  mut amount : Double?
  mut customer : User?
  mut related_orders : Array[Order]
} derive(Eq, Show)
pub impl @protobuf.Sized for Order with size_of(self) {
  let mut size = 0U
  size += 1U + { let size = @protobuf.size_of(self.order_id); @protobuf.size_of(size) + size }
  size += 1U + { let size = @protobuf.size_of(self.product_name); @protobuf.size_of(size) + size }
  match self.amount {
    Some(v) => size += 1U + 8U
    None => ()
  }
  match self.customer {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size += self.related_orders.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size
}
pub impl Default for Order with default() -> Order {
  Order::{
    order_id : String::default(),
    product_name : String::default(),
    amount : None,
    customer : None,
    related_orders : [],
  }
}
pub async fn[R: @protobuf.AsyncReader] Order::read(reader : R) -> Order raise {
  let reader = @protobuf.LimitedReader::new(reader)
  Order::read_with_limit(reader)
}
pub async fn[R: @protobuf.AsyncReader] Order::read_with_limit(reader : @protobuf.LimitedReader[R], limit ?: Int) -> Order raise {
  let new_limit = if reader.limit is Some(l) && limit is Some(limit) {
    if l < limit { raise @protobuf.EndOfStream }
    Some(l - limit)
  } else { None }
  reader.limit = limit
  let msg = Order::default()
  try {
    for {
      match (reader |> @protobuf.async_read_tag()) {
      (1, _) => msg.order_id = reader |> @protobuf.async_read_string()
      (2, _) => msg.product_name = reader |> @protobuf.async_read_string()
      (3, _) => msg.amount = reader |> @protobuf.async_read_double() |> Some
      (4, _) => msg.customer =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      User::default()
    } else {
      User::read_with_limit(reader, limit=len)
    }
  } |> Some
      (5, _) => msg.related_orders.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Order::default()
    } else {
      Order::read_with_limit(reader, limit=len)
    }
  })
       (_, wire) => reader |> @protobuf.async_read_unknown(wire)
      }
    }
  } catch {
    @protobuf.EndOfStream => ()
    err => raise err
  }
  reader.limit = new_limit
  msg
}
pub async fn[W: @protobuf.AsyncWriter] Order::write(self:Self, writer : W) -> Unit raise {
  writer |> @protobuf.async_write_varint(10UL);writer |> @protobuf.async_write_string(self.order_id)
  writer |> @protobuf.async_write_varint(18UL);writer |> @protobuf.async_write_string(self.product_name)
  match self.amount {
    Some(v) => {
      writer |> @protobuf.async_write_varint(25UL);writer |> @protobuf.async_write_double(v)
    }
    None => ()
  }
  match self.customer {
    Some(v) => {
      writer |> @protobuf.async_write_varint(34UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
  for i in 0..<self.related_orders.length() {
        writer |> @protobuf.async_write_varint(42UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.related_orders[i])); self.related_orders[i].write(writer)
  }
}
pub impl ToJson for Order with to_json(self) {

  let json: Map[String, Json] = {}
  if self.order_id != Default::default() {
  json["orderId"] = self.order_id.to_json()
  }
  if self.product_name != Default::default() {
  json["productName"] = self.product_name.to_json()
  }
  match self.amount {
      Some(v) => json["amount"] = v.to_json()
      _ => ()
    }
  match self.customer {
      Some(v) => json["customer"] = v.to_json()
      _ => ()
    }
  if self.related_orders != Default::default() {
  json["relatedOrders"] = self.related_orders.to_json()
  }
  Json::object(json)
}
pub impl @json.FromJson for Order with from_json(json: Json, path: @json.JsonPath) -> Order raise {
  guard json is Object(obj) else {
    raise @json.JsonDecodeError((path, "Expected an object for Order"))
  }
  let message = Order::default()

  for key, value in obj {
    match (key, value) {
      ("orderId", value) => message.order_id = @json.from_json(value, path~)
      ("productName", value) => message.product_name = @json.from_json(value, path~)
      ("amount", value) => message.amount = Some(@json.from_json(value, path~))
      ("customer", value) => message.customer = Some(@json.from_json(value, path~))
      ("relatedOrders", Array(value)) => message.related_orders = value.map(v => 
@json.from_json(v, path~))
      key => raise @json.JsonDecodeError((path, "Unknown field \{key}"))
      }
  }
  message
}
pub(all) struct Department {
  mut dept_id : String
  mut name : String
  mut employees : Array[Employee]
  mut projects : Array[Project]
  mut parent_dept : Department?
} derive(Eq, Show)
pub impl @protobuf.Sized for Department with size_of(self) {
  let mut size = 0U
  size += 1U + { let size = @protobuf.size_of(self.dept_id); @protobuf.size_of(size) + size }
  size += 1U + { let size = @protobuf.size_of(self.name); @protobuf.size_of(size) + size }
  size += self.employees.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size += self.projects.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  match self.parent_dept {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size
}
pub impl Default for Department with default() -> Department {
  Department::{
    dept_id : String::default(),
    name : String::default(),
    employees : [],
    projects : [],
    parent_dept : None,
  }
}
pub async fn[R: @protobuf.AsyncReader] Department::read(reader : R) -> Department raise {
  let reader = @protobuf.LimitedReader::new(reader)
  Department::read_with_limit(reader)
}
pub async fn[R: @protobuf.AsyncReader] Department::read_with_limit(reader : @protobuf.LimitedReader[R], limit ?: Int) -> Department raise {
  let new_limit = if reader.limit is Some(l) && limit is Some(limit) {
    if l < limit { raise @protobuf.EndOfStream }
    Some(l - limit)
  } else { None }
  reader.limit = limit
  let msg = Department::default()
  try {
    for {
      match (reader |> @protobuf.async_read_tag()) {
      (1, _) => msg.dept_id = reader |> @protobuf.async_read_string()
      (2, _) => msg.name = reader |> @protobuf.async_read_string()
      (3, _) => msg.employees.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Employee::default()
    } else {
      Employee::read_with_limit(reader, limit=len)
    }
  })
      (4, _) => msg.projects.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Project::default()
    } else {
      Project::read_with_limit(reader, limit=len)
    }
  })
      (5, _) => msg.parent_dept =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Department::default()
    } else {
      Department::read_with_limit(reader, limit=len)
    }
  } |> Some
       (_, wire) => reader |> @protobuf.async_read_unknown(wire)
      }
    }
  } catch {
    @protobuf.EndOfStream => ()
    err => raise err
  }
  reader.limit = new_limit
  msg
}
pub async fn[W: @protobuf.AsyncWriter] Department::write(self:Self, writer : W) -> Unit raise {
  writer |> @protobuf.async_write_varint(10UL);writer |> @protobuf.async_write_string(self.dept_id)
  writer |> @protobuf.async_write_varint(18UL);writer |> @protobuf.async_write_string(self.name)
  for i in 0..<self.employees.length() {
        writer |> @protobuf.async_write_varint(26UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.employees[i])); self.employees[i].write(writer)
  }
  for i in 0..<self.projects.length() {
        writer |> @protobuf.async_write_varint(34UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.projects[i])); self.projects[i].write(writer)
  }
  match self.parent_dept {
    Some(v) => {
      writer |> @protobuf.async_write_varint(42UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
}
pub impl ToJson for Department with to_json(self) {

  let json: Map[String, Json] = {}
  if self.dept_id != Default::default() {
  json["deptId"] = self.dept_id.to_json()
  }
  if self.name != Default::default() {
  json["name"] = self.name.to_json()
  }
  if self.employees != Default::default() {
  json["employees"] = self.employees.to_json()
  }
  if self.projects != Default::default() {
  json["projects"] = self.projects.to_json()
  }
  match self.parent_dept {
      Some(v) => json["parentDept"] = v.to_json()
      _ => ()
    }
  Json::object(json)
}
pub impl @json.FromJson for Department with from_json(json: Json, path: @json.JsonPath) -> Department raise {
  guard json is Object(obj) else {
    raise @json.JsonDecodeError((path, "Expected an object for Department"))
  }
  let message = Department::default()

  for key, value in obj {
    match (key, value) {
      ("deptId", value) => message.dept_id = @json.from_json(value, path~)
      ("name", value) => message.name = @json.from_json(value, path~)
      ("employees", Array(value)) => message.employees = value.map(v => 
@json.from_json(v, path~))
      ("projects", Array(value)) => message.projects = value.map(v => 
@json.from_json(v, path~))
      ("parentDept", value) => message.parent_dept = Some(@json.from_json(value, path~))
      key => raise @json.JsonDecodeError((path, "Unknown field \{key}"))
      }
  }
  message
}
pub(all) struct Employee {
  mut emp_id : String
  mut name : String
  mut department : Department?
  mut projects : Array[Project]
  mut supervisor : Employee?
  mut subordinates : Array[Employee]
} derive(Eq, Show)
pub impl @protobuf.Sized for Employee with size_of(self) {
  let mut size = 0U
  size += 1U + { let size = @protobuf.size_of(self.emp_id); @protobuf.size_of(size) + size }
  size += 1U + { let size = @protobuf.size_of(self.name); @protobuf.size_of(size) + size }
  match self.department {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size += self.projects.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  match self.supervisor {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size += self.subordinates.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size
}
pub impl Default for Employee with default() -> Employee {
  Employee::{
    emp_id : String::default(),
    name : String::default(),
    department : None,
    projects : [],
    supervisor : None,
    subordinates : [],
  }
}
pub async fn[R: @protobuf.AsyncReader] Employee::read(reader : R) -> Employee raise {
  let reader = @protobuf.LimitedReader::new(reader)
  Employee::read_with_limit(reader)
}
pub async fn[R: @protobuf.AsyncReader] Employee::read_with_limit(reader : @protobuf.LimitedReader[R], limit ?: Int) -> Employee raise {
  let new_limit = if reader.limit is Some(l) && limit is Some(limit) {
    if l < limit { raise @protobuf.EndOfStream }
    Some(l - limit)
  } else { None }
  reader.limit = limit
  let msg = Employee::default()
  try {
    for {
      match (reader |> @protobuf.async_read_tag()) {
      (1, _) => msg.emp_id = reader |> @protobuf.async_read_string()
      (2, _) => msg.name = reader |> @protobuf.async_read_string()
      (3, _) => msg.department =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Department::default()
    } else {
      Department::read_with_limit(reader, limit=len)
    }
  } |> Some
      (4, _) => msg.projects.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Project::default()
    } else {
      Project::read_with_limit(reader, limit=len)
    }
  })
      (5, _) => msg.supervisor =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Employee::default()
    } else {
      Employee::read_with_limit(reader, limit=len)
    }
  } |> Some
      (6, _) => msg.subordinates.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Employee::default()
    } else {
      Employee::read_with_limit(reader, limit=len)
    }
  })
       (_, wire) => reader |> @protobuf.async_read_unknown(wire)
      }
    }
  } catch {
    @protobuf.EndOfStream => ()
    err => raise err
  }
  reader.limit = new_limit
  msg
}
pub async fn[W: @protobuf.AsyncWriter] Employee::write(self:Self, writer : W) -> Unit raise {
  writer |> @protobuf.async_write_varint(10UL);writer |> @protobuf.async_write_string(self.emp_id)
  writer |> @protobuf.async_write_varint(18UL);writer |> @protobuf.async_write_string(self.name)
  match self.department {
    Some(v) => {
      writer |> @protobuf.async_write_varint(26UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
  for i in 0..<self.projects.length() {
        writer |> @protobuf.async_write_varint(34UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.projects[i])); self.projects[i].write(writer)
  }
  match self.supervisor {
    Some(v) => {
      writer |> @protobuf.async_write_varint(42UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
  for i in 0..<self.subordinates.length() {
        writer |> @protobuf.async_write_varint(50UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.subordinates[i])); self.subordinates[i].write(writer)
  }
}
pub impl ToJson for Employee with to_json(self) {

  let json: Map[String, Json] = {}
  if self.emp_id != Default::default() {
  json["empId"] = self.emp_id.to_json()
  }
  if self.name != Default::default() {
  json["name"] = self.name.to_json()
  }
  match self.department {
      Some(v) => json["department"] = v.to_json()
      _ => ()
    }
  if self.projects != Default::default() {
  json["projects"] = self.projects.to_json()
  }
  match self.supervisor {
      Some(v) => json["supervisor"] = v.to_json()
      _ => ()
    }
  if self.subordinates != Default::default() {
  json["subordinates"] = self.subordinates.to_json()
  }
  Json::object(json)
}
pub impl @json.FromJson for Employee with from_json(json: Json, path: @json.JsonPath) -> Employee raise {
  guard json is Object(obj) else {
    raise @json.JsonDecodeError((path, "Expected an object for Employee"))
  }
  let message = Employee::default()

  for key, value in obj {
    match (key, value) {
      ("empId", value) => message.emp_id = @json.from_json(value, path~)
      ("name", value) => message.name = @json.from_json(value, path~)
      ("department", value) => message.department = Some(@json.from_json(value, path~))
      ("projects", Array(value)) => message.projects = value.map(v => 
@json.from_json(v, path~))
      ("supervisor", value) => message.supervisor = Some(@json.from_json(value, path~))
      ("subordinates", Array(value)) => message.subordinates = value.map(v => 
@json.from_json(v, path~))
      key => raise @json.JsonDecodeError((path, "Unknown field \{key}"))
      }
  }
  message
}
pub(all) struct Project {
  mut project_id : String
  mut title : String
  mut description : String?
  mut department : Department?
  mut members : Array[Employee]
  mut dependencies : Array[Project]
  mut dependents : Array[Project]
} derive(Eq, Show)
pub impl @protobuf.Sized for Project with size_of(self) {
  let mut size = 0U
  size += 1U + { let size = @protobuf.size_of(self.project_id); @protobuf.size_of(size) + size }
  size += 1U + { let size = @protobuf.size_of(self.title); @protobuf.size_of(size) + size }
  match self.description {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  match self.department {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size += self.members.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size += self.dependencies.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size += self.dependents.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size
}
pub impl Default for Project with default() -> Project {
  Project::{
    project_id : String::default(),
    title : String::default(),
    description : None,
    department : None,
    members : [],
    dependencies : [],
    dependents : [],
  }
}
pub async fn[R: @protobuf.AsyncReader] Project::read(reader : R) -> Project raise {
  let reader = @protobuf.LimitedReader::new(reader)
  Project::read_with_limit(reader)
}
pub async fn[R: @protobuf.AsyncReader] Project::read_with_limit(reader : @protobuf.LimitedReader[R], limit ?: Int) -> Project raise {
  let new_limit = if reader.limit is Some(l) && limit is Some(limit) {
    if l < limit { raise @protobuf.EndOfStream }
    Some(l - limit)
  } else { None }
  reader.limit = limit
  let msg = Project::default()
  try {
    for {
      match (reader |> @protobuf.async_read_tag()) {
      (1, _) => msg.project_id = reader |> @protobuf.async_read_string()
      (2, _) => msg.title = reader |> @protobuf.async_read_string()
      (3, _) => msg.description = reader |> @protobuf.async_read_string() |> Some
      (4, _) => msg.department =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Department::default()
    } else {
      Department::read_with_limit(reader, limit=len)
    }
  } |> Some
      (5, _) => msg.members.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Employee::default()
    } else {
      Employee::read_with_limit(reader, limit=len)
    }
  })
      (6, _) => msg.dependencies.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Project::default()
    } else {
      Project::read_with_limit(reader, limit=len)
    }
  })
      (7, _) => msg.dependents.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Project::default()
    } else {
      Project::read_with_limit(reader, limit=len)
    }
  })
       (_, wire) => reader |> @protobuf.async_read_unknown(wire)
      }
    }
  } catch {
    @protobuf.EndOfStream => ()
    err => raise err
  }
  reader.limit = new_limit
  msg
}
pub async fn[W: @protobuf.AsyncWriter] Project::write(self:Self, writer : W) -> Unit raise {
  writer |> @protobuf.async_write_varint(10UL);writer |> @protobuf.async_write_string(self.project_id)
  writer |> @protobuf.async_write_varint(18UL);writer |> @protobuf.async_write_string(self.title)
  match self.description {
    Some(v) => {
      writer |> @protobuf.async_write_varint(26UL);writer |> @protobuf.async_write_string(v)
    }
    None => ()
  }
  match self.department {
    Some(v) => {
      writer |> @protobuf.async_write_varint(34UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
  for i in 0..<self.members.length() {
        writer |> @protobuf.async_write_varint(42UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.members[i])); self.members[i].write(writer)
  }
  for i in 0..<self.dependencies.length() {
        writer |> @protobuf.async_write_varint(50UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.dependencies[i])); self.dependencies[i].write(writer)
  }
  for i in 0..<self.dependents.length() {
        writer |> @protobuf.async_write_varint(58UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.dependents[i])); self.dependents[i].write(writer)
  }
}
pub impl ToJson for Project with to_json(self) {

  let json: Map[String, Json] = {}
  if self.project_id != Default::default() {
  json["projectId"] = self.project_id.to_json()
  }
  if self.title != Default::default() {
  json["title"] = self.title.to_json()
  }
  match self.description {
      Some(v) => json["description"] = v.to_json()
      _ => ()
    }
  match self.department {
      Some(v) => json["department"] = v.to_json()
      _ => ()
    }
  if self.members != Default::default() {
  json["members"] = self.members.to_json()
  }
  if self.dependencies != Default::default() {
  json["dependencies"] = self.dependencies.to_json()
  }
  if self.dependents != Default::default() {
  json["dependents"] = self.dependents.to_json()
  }
  Json::object(json)
}
pub impl @json.FromJson for Project with from_json(json: Json, path: @json.JsonPath) -> Project raise {
  guard json is Object(obj) else {
    raise @json.JsonDecodeError((path, "Expected an object for Project"))
  }
  let message = Project::default()

  for key, value in obj {
    match (key, value) {
      ("projectId", value) => message.project_id = @json.from_json(value, path~)
      ("title", value) => message.title = @json.from_json(value, path~)
      ("description", value) => message.description = Some(@json.from_json(value, path~))
      ("department", value) => message.department = Some(@json.from_json(value, path~))
      ("members", Array(value)) => message.members = value.map(v => 
@json.from_json(v, path~))
      ("dependencies", Array(value)) => message.dependencies = value.map(v => 
@json.from_json(v, path~))
      ("dependents", Array(value)) => message.dependents = value.map(v => 
@json.from_json(v, path~))
      key => raise @json.JsonDecodeError((path, "Unknown field \{key}"))
      }
  }
  message
}
pub(all) struct Node_Connection {
  mut connection_id : String
  mut type_ : String?
  mut source : Node?
  mut target : Node?
  mut weight : Weight?
} derive(Eq, Show)
pub impl @protobuf.Sized for Node_Connection with size_of(self) {
  let mut size = 0U
  size += 1U + { let size = @protobuf.size_of(self.connection_id); @protobuf.size_of(size) + size }
  match self.type_ {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  match self.source {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  match self.target {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  match self.weight {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size
}
pub impl Default for Node_Connection with default() -> Node_Connection {
  Node_Connection::{
    connection_id : String::default(),
    type_ : None,
    source : None,
    target : None,
    weight : None,
  }
}
pub async fn[R: @protobuf.AsyncReader] Node_Connection::read(reader : R) -> Node_Connection raise {
  let reader = @protobuf.LimitedReader::new(reader)
  Node_Connection::read_with_limit(reader)
}
pub async fn[R: @protobuf.AsyncReader] Node_Connection::read_with_limit(reader : @protobuf.LimitedReader[R], limit ?: Int) -> Node_Connection raise {
  let new_limit = if reader.limit is Some(l) && limit is Some(limit) {
    if l < limit { raise @protobuf.EndOfStream }
    Some(l - limit)
  } else { None }
  reader.limit = limit
  let msg = Node_Connection::default()
  try {
    for {
      match (reader |> @protobuf.async_read_tag()) {
      (1, _) => msg.connection_id = reader |> @protobuf.async_read_string()
      (2, _) => msg.type_ = reader |> @protobuf.async_read_string() |> Some
      (3, _) => msg.source =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Node::default()
    } else {
      Node::read_with_limit(reader, limit=len)
    }
  } |> Some
      (4, _) => msg.target =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Node::default()
    } else {
      Node::read_with_limit(reader, limit=len)
    }
  } |> Some
      (5, _) => msg.weight =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Weight::default()
    } else {
      Weight::read_with_limit(reader, limit=len)
    }
  } |> Some
       (_, wire) => reader |> @protobuf.async_read_unknown(wire)
      }
    }
  } catch {
    @protobuf.EndOfStream => ()
    err => raise err
  }
  reader.limit = new_limit
  msg
}
pub async fn[W: @protobuf.AsyncWriter] Node_Connection::write(self:Self, writer : W) -> Unit raise {
  writer |> @protobuf.async_write_varint(10UL);writer |> @protobuf.async_write_string(self.connection_id)
  match self.type_ {
    Some(v) => {
      writer |> @protobuf.async_write_varint(18UL);writer |> @protobuf.async_write_string(v)
    }
    None => ()
  }
  match self.source {
    Some(v) => {
      writer |> @protobuf.async_write_varint(26UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
  match self.target {
    Some(v) => {
      writer |> @protobuf.async_write_varint(34UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
  match self.weight {
    Some(v) => {
      writer |> @protobuf.async_write_varint(42UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
}
pub impl ToJson for Node_Connection with to_json(self) {

  let json: Map[String, Json] = {}
  if self.connection_id != Default::default() {
  json["connectionId"] = self.connection_id.to_json()
  }
  match self.type_ {
      Some(v) => json["type"] = v.to_json()
      _ => ()
    }
  match self.source {
      Some(v) => json["source"] = v.to_json()
      _ => ()
    }
  match self.target {
      Some(v) => json["target"] = v.to_json()
      _ => ()
    }
  match self.weight {
      Some(v) => json["weight"] = v.to_json()
      _ => ()
    }
  Json::object(json)
}
pub impl @json.FromJson for Node_Connection with from_json(json: Json, path: @json.JsonPath) -> Node_Connection raise {
  guard json is Object(obj) else {
    raise @json.JsonDecodeError((path, "Expected an object for Node_Connection"))
  }
  let message = Node_Connection::default()

  for key, value in obj {
    match (key, value) {
      ("connectionId", value) => message.connection_id = @json.from_json(value, path~)
      ("type", value) => message.type_ = Some(@json.from_json(value, path~))
      ("source", value) => message.source = Some(@json.from_json(value, path~))
      ("target", value) => message.target = Some(@json.from_json(value, path~))
      ("weight", value) => message.weight = Some(@json.from_json(value, path~))
      key => raise @json.JsonDecodeError((path, "Unknown field \{key}"))
      }
  }
  message
}
pub(all) struct Node {
  mut id : String
  mut data : String?
  mut connections : Array[Node_Connection]
  mut neighbors : Array[Node]
} derive(Eq, Show)
pub impl @protobuf.Sized for Node with size_of(self) {
  let mut size = 0U
  size += 1U + { let size = @protobuf.size_of(self.id); @protobuf.size_of(size) + size }
  match self.data {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size += self.connections.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size += self.neighbors.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size
}
pub impl Default for Node with default() -> Node {
  Node::{
    id : String::default(),
    data : None,
    connections : [],
    neighbors : [],
  }
}
pub async fn[R: @protobuf.AsyncReader] Node::read(reader : R) -> Node raise {
  let reader = @protobuf.LimitedReader::new(reader)
  Node::read_with_limit(reader)
}
pub async fn[R: @protobuf.AsyncReader] Node::read_with_limit(reader : @protobuf.LimitedReader[R], limit ?: Int) -> Node raise {
  let new_limit = if reader.limit is Some(l) && limit is Some(limit) {
    if l < limit { raise @protobuf.EndOfStream }
    Some(l - limit)
  } else { None }
  reader.limit = limit
  let msg = Node::default()
  try {
    for {
      match (reader |> @protobuf.async_read_tag()) {
      (1, _) => msg.id = reader |> @protobuf.async_read_string()
      (2, _) => msg.data = reader |> @protobuf.async_read_string() |> Some
      (3, _) => msg.connections.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Node_Connection::default()
    } else {
      Node_Connection::read_with_limit(reader, limit=len)
    }
  })
      (4, _) => msg.neighbors.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Node::default()
    } else {
      Node::read_with_limit(reader, limit=len)
    }
  })
       (_, wire) => reader |> @protobuf.async_read_unknown(wire)
      }
    }
  } catch {
    @protobuf.EndOfStream => ()
    err => raise err
  }
  reader.limit = new_limit
  msg
}
pub async fn[W: @protobuf.AsyncWriter] Node::write(self:Self, writer : W) -> Unit raise {
  writer |> @protobuf.async_write_varint(10UL);writer |> @protobuf.async_write_string(self.id)
  match self.data {
    Some(v) => {
      writer |> @protobuf.async_write_varint(18UL);writer |> @protobuf.async_write_string(v)
    }
    None => ()
  }
  for i in 0..<self.connections.length() {
        writer |> @protobuf.async_write_varint(26UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.connections[i])); self.connections[i].write(writer)
  }
  for i in 0..<self.neighbors.length() {
        writer |> @protobuf.async_write_varint(34UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.neighbors[i])); self.neighbors[i].write(writer)
  }
}
pub impl ToJson for Node with to_json(self) {

  let json: Map[String, Json] = {}
  if self.id != Default::default() {
  json["id"] = self.id.to_json()
  }
  match self.data {
      Some(v) => json["data"] = v.to_json()
      _ => ()
    }
  if self.connections != Default::default() {
  json["connections"] = self.connections.to_json()
  }
  if self.neighbors != Default::default() {
  json["neighbors"] = self.neighbors.to_json()
  }
  Json::object(json)
}
pub impl @json.FromJson for Node with from_json(json: Json, path: @json.JsonPath) -> Node raise {
  guard json is Object(obj) else {
    raise @json.JsonDecodeError((path, "Expected an object for Node"))
  }
  let message = Node::default()

  for key, value in obj {
    match (key, value) {
      ("id", value) => message.id = @json.from_json(value, path~)
      ("data", value) => message.data = Some(@json.from_json(value, path~))
      ("connections", Array(value)) => message.connections = value.map(v => 
@json.from_json(v, path~))
      ("neighbors", Array(value)) => message.neighbors = value.map(v => 
@json.from_json(v, path~))
      key => raise @json.JsonDecodeError((path, "Unknown field \{key}"))
      }
  }
  message
}
pub(all) struct Weight {
  mut value : Double
  mut unit : String?
  mut connection : Node_Connection?
  mut related_nodes : Array[Node]
} derive(Eq, Show)
pub impl @protobuf.Sized for Weight with size_of(self) {
  let mut size = 0U
  size += 1U + 8U
  match self.unit {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  match self.connection {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size += self.related_nodes.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size
}
pub impl Default for Weight with default() -> Weight {
  Weight::{
    value : Double::default(),
    unit : None,
    connection : None,
    related_nodes : [],
  }
}
pub async fn[R: @protobuf.AsyncReader] Weight::read(reader : R) -> Weight raise {
  let reader = @protobuf.LimitedReader::new(reader)
  Weight::read_with_limit(reader)
}
pub async fn[R: @protobuf.AsyncReader] Weight::read_with_limit(reader : @protobuf.LimitedReader[R], limit ?: Int) -> Weight raise {
  let new_limit = if reader.limit is Some(l) && limit is Some(limit) {
    if l < limit { raise @protobuf.EndOfStream }
    Some(l - limit)
  } else { None }
  reader.limit = limit
  let msg = Weight::default()
  try {
    for {
      match (reader |> @protobuf.async_read_tag()) {
      (1, _) => msg.value = reader |> @protobuf.async_read_double()
      (2, _) => msg.unit = reader |> @protobuf.async_read_string() |> Some
      (3, _) => msg.connection =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Node_Connection::default()
    } else {
      Node_Connection::read_with_limit(reader, limit=len)
    }
  } |> Some
      (4, _) => msg.related_nodes.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Node::default()
    } else {
      Node::read_with_limit(reader, limit=len)
    }
  })
       (_, wire) => reader |> @protobuf.async_read_unknown(wire)
      }
    }
  } catch {
    @protobuf.EndOfStream => ()
    err => raise err
  }
  reader.limit = new_limit
  msg
}
pub async fn[W: @protobuf.AsyncWriter] Weight::write(self:Self, writer : W) -> Unit raise {
  writer |> @protobuf.async_write_varint(9UL);writer |> @protobuf.async_write_double(self.value)
  match self.unit {
    Some(v) => {
      writer |> @protobuf.async_write_varint(18UL);writer |> @protobuf.async_write_string(v)
    }
    None => ()
  }
  match self.connection {
    Some(v) => {
      writer |> @protobuf.async_write_varint(26UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
  for i in 0..<self.related_nodes.length() {
        writer |> @protobuf.async_write_varint(34UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.related_nodes[i])); self.related_nodes[i].write(writer)
  }
}
pub impl ToJson for Weight with to_json(self) {

  let json: Map[String, Json] = {}
  if self.value != Default::default() {
  json["value"] = self.value.to_json()
  }
  match self.unit {
      Some(v) => json["unit"] = v.to_json()
      _ => ()
    }
  match self.connection {
      Some(v) => json["connection"] = v.to_json()
      _ => ()
    }
  if self.related_nodes != Default::default() {
  json["relatedNodes"] = self.related_nodes.to_json()
  }
  Json::object(json)
}
pub impl @json.FromJson for Weight with from_json(json: Json, path: @json.JsonPath) -> Weight raise {
  guard json is Object(obj) else {
    raise @json.JsonDecodeError((path, "Expected an object for Weight"))
  }
  let message = Weight::default()

  for key, value in obj {
    match (key, value) {
      ("value", value) => message.value = @json.from_json(value, path~)
      ("unit", value) => message.unit = Some(@json.from_json(value, path~))
      ("connection", value) => message.connection = Some(@json.from_json(value, path~))
      ("relatedNodes", Array(value)) => message.related_nodes = value.map(v => 
@json.from_json(v, path~))
      key => raise @json.JsonDecodeError((path, "Unknown field \{key}"))
      }
  }
  message
}
pub(all) struct Graph {
  mut graph_id : String
  mut name : String?
  mut vertices : Array[Vertex]
  mut edges : Array[Edge]
} derive(Eq, Show)
pub impl @protobuf.Sized for Graph with size_of(self) {
  let mut size = 0U
  size += 1U + { let size = @protobuf.size_of(self.graph_id); @protobuf.size_of(size) + size }
  match self.name {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size += self.vertices.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size += self.edges.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size
}
pub impl Default for Graph with default() -> Graph {
  Graph::{
    graph_id : String::default(),
    name : None,
    vertices : [],
    edges : [],
  }
}
pub async fn[R: @protobuf.AsyncReader] Graph::read(reader : R) -> Graph raise {
  let reader = @protobuf.LimitedReader::new(reader)
  Graph::read_with_limit(reader)
}
pub async fn[R: @protobuf.AsyncReader] Graph::read_with_limit(reader : @protobuf.LimitedReader[R], limit ?: Int) -> Graph raise {
  let new_limit = if reader.limit is Some(l) && limit is Some(limit) {
    if l < limit { raise @protobuf.EndOfStream }
    Some(l - limit)
  } else { None }
  reader.limit = limit
  let msg = Graph::default()
  try {
    for {
      match (reader |> @protobuf.async_read_tag()) {
      (1, _) => msg.graph_id = reader |> @protobuf.async_read_string()
      (2, _) => msg.name = reader |> @protobuf.async_read_string() |> Some
      (3, _) => msg.vertices.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Vertex::default()
    } else {
      Vertex::read_with_limit(reader, limit=len)
    }
  })
      (4, _) => msg.edges.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Edge::default()
    } else {
      Edge::read_with_limit(reader, limit=len)
    }
  })
       (_, wire) => reader |> @protobuf.async_read_unknown(wire)
      }
    }
  } catch {
    @protobuf.EndOfStream => ()
    err => raise err
  }
  reader.limit = new_limit
  msg
}
pub async fn[W: @protobuf.AsyncWriter] Graph::write(self:Self, writer : W) -> Unit raise {
  writer |> @protobuf.async_write_varint(10UL);writer |> @protobuf.async_write_string(self.graph_id)
  match self.name {
    Some(v) => {
      writer |> @protobuf.async_write_varint(18UL);writer |> @protobuf.async_write_string(v)
    }
    None => ()
  }
  for i in 0..<self.vertices.length() {
        writer |> @protobuf.async_write_varint(26UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.vertices[i])); self.vertices[i].write(writer)
  }
  for i in 0..<self.edges.length() {
        writer |> @protobuf.async_write_varint(34UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.edges[i])); self.edges[i].write(writer)
  }
}
pub impl ToJson for Graph with to_json(self) {

  let json: Map[String, Json] = {}
  if self.graph_id != Default::default() {
  json["graphId"] = self.graph_id.to_json()
  }
  match self.name {
      Some(v) => json["name"] = v.to_json()
      _ => ()
    }
  if self.vertices != Default::default() {
  json["vertices"] = self.vertices.to_json()
  }
  if self.edges != Default::default() {
  json["edges"] = self.edges.to_json()
  }
  Json::object(json)
}
pub impl @json.FromJson for Graph with from_json(json: Json, path: @json.JsonPath) -> Graph raise {
  guard json is Object(obj) else {
    raise @json.JsonDecodeError((path, "Expected an object for Graph"))
  }
  let message = Graph::default()

  for key, value in obj {
    match (key, value) {
      ("graphId", value) => message.graph_id = @json.from_json(value, path~)
      ("name", value) => message.name = Some(@json.from_json(value, path~))
      ("vertices", Array(value)) => message.vertices = value.map(v => 
@json.from_json(v, path~))
      ("edges", Array(value)) => message.edges = value.map(v => 
@json.from_json(v, path~))
      key => raise @json.JsonDecodeError((path, "Unknown field \{key}"))
      }
  }
  message
}
pub(all) struct Vertex {
  mut vertex_id : String
  mut label : String?
  mut graph : Graph?
  mut incoming_edges : Array[Edge]
  mut outgoing_edges : Array[Edge]
  mut adjacent_vertices : Array[Vertex]
} derive(Eq, Show)
pub impl @protobuf.Sized for Vertex with size_of(self) {
  let mut size = 0U
  size += 1U + { let size = @protobuf.size_of(self.vertex_id); @protobuf.size_of(size) + size }
  match self.label {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  match self.graph {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size += self.incoming_edges.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size += self.outgoing_edges.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size += self.adjacent_vertices.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size
}
pub impl Default for Vertex with default() -> Vertex {
  Vertex::{
    vertex_id : String::default(),
    label : None,
    graph : None,
    incoming_edges : [],
    outgoing_edges : [],
    adjacent_vertices : [],
  }
}
pub async fn[R: @protobuf.AsyncReader] Vertex::read(reader : R) -> Vertex raise {
  let reader = @protobuf.LimitedReader::new(reader)
  Vertex::read_with_limit(reader)
}
pub async fn[R: @protobuf.AsyncReader] Vertex::read_with_limit(reader : @protobuf.LimitedReader[R], limit ?: Int) -> Vertex raise {
  let new_limit = if reader.limit is Some(l) && limit is Some(limit) {
    if l < limit { raise @protobuf.EndOfStream }
    Some(l - limit)
  } else { None }
  reader.limit = limit
  let msg = Vertex::default()
  try {
    for {
      match (reader |> @protobuf.async_read_tag()) {
      (1, _) => msg.vertex_id = reader |> @protobuf.async_read_string()
      (2, _) => msg.label = reader |> @protobuf.async_read_string() |> Some
      (3, _) => msg.graph =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Graph::default()
    } else {
      Graph::read_with_limit(reader, limit=len)
    }
  } |> Some
      (4, _) => msg.incoming_edges.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Edge::default()
    } else {
      Edge::read_with_limit(reader, limit=len)
    }
  })
      (5, _) => msg.outgoing_edges.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Edge::default()
    } else {
      Edge::read_with_limit(reader, limit=len)
    }
  })
      (6, _) => msg.adjacent_vertices.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Vertex::default()
    } else {
      Vertex::read_with_limit(reader, limit=len)
    }
  })
       (_, wire) => reader |> @protobuf.async_read_unknown(wire)
      }
    }
  } catch {
    @protobuf.EndOfStream => ()
    err => raise err
  }
  reader.limit = new_limit
  msg
}
pub async fn[W: @protobuf.AsyncWriter] Vertex::write(self:Self, writer : W) -> Unit raise {
  writer |> @protobuf.async_write_varint(10UL);writer |> @protobuf.async_write_string(self.vertex_id)
  match self.label {
    Some(v) => {
      writer |> @protobuf.async_write_varint(18UL);writer |> @protobuf.async_write_string(v)
    }
    None => ()
  }
  match self.graph {
    Some(v) => {
      writer |> @protobuf.async_write_varint(26UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
  for i in 0..<self.incoming_edges.length() {
        writer |> @protobuf.async_write_varint(34UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.incoming_edges[i])); self.incoming_edges[i].write(writer)
  }
  for i in 0..<self.outgoing_edges.length() {
        writer |> @protobuf.async_write_varint(42UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.outgoing_edges[i])); self.outgoing_edges[i].write(writer)
  }
  for i in 0..<self.adjacent_vertices.length() {
        writer |> @protobuf.async_write_varint(50UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.adjacent_vertices[i])); self.adjacent_vertices[i].write(writer)
  }
}
pub impl ToJson for Vertex with to_json(self) {

  let json: Map[String, Json] = {}
  if self.vertex_id != Default::default() {
  json["vertexId"] = self.vertex_id.to_json()
  }
  match self.label {
      Some(v) => json["label"] = v.to_json()
      _ => ()
    }
  match self.graph {
      Some(v) => json["graph"] = v.to_json()
      _ => ()
    }
  if self.incoming_edges != Default::default() {
  json["incomingEdges"] = self.incoming_edges.to_json()
  }
  if self.outgoing_edges != Default::default() {
  json["outgoingEdges"] = self.outgoing_edges.to_json()
  }
  if self.adjacent_vertices != Default::default() {
  json["adjacentVertices"] = self.adjacent_vertices.to_json()
  }
  Json::object(json)
}
pub impl @json.FromJson for Vertex with from_json(json: Json, path: @json.JsonPath) -> Vertex raise {
  guard json is Object(obj) else {
    raise @json.JsonDecodeError((path, "Expected an object for Vertex"))
  }
  let message = Vertex::default()

  for key, value in obj {
    match (key, value) {
      ("vertexId", value) => message.vertex_id = @json.from_json(value, path~)
      ("label", value) => message.label = Some(@json.from_json(value, path~))
      ("graph", value) => message.graph = Some(@json.from_json(value, path~))
      ("incomingEdges", Array(value)) => message.incoming_edges = value.map(v => 
@json.from_json(v, path~))
      ("outgoingEdges", Array(value)) => message.outgoing_edges = value.map(v => 
@json.from_json(v, path~))
      ("adjacentVertices", Array(value)) => message.adjacent_vertices = value.map(v => 
@json.from_json(v, path~))
      key => raise @json.JsonDecodeError((path, "Unknown field \{key}"))
      }
  }
  message
}
pub(all) struct Edge {
  mut edge_id : String
  mut weight : Double?
  mut graph : Graph?
  mut source_vertex : Vertex?
  mut target_vertex : Vertex?
  mut parallel_edges : Array[Edge]
} derive(Eq, Show)
pub impl @protobuf.Sized for Edge with size_of(self) {
  let mut size = 0U
  size += 1U + { let size = @protobuf.size_of(self.edge_id); @protobuf.size_of(size) + size }
  match self.weight {
    Some(v) => size += 1U + 8U
    None => ()
  }
  match self.graph {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  match self.source_vertex {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  match self.target_vertex {
    Some(v) => size += 1U + { let size = @protobuf.size_of(v); @protobuf.size_of(size) + size }
    None => ()
  }
  size += self.parallel_edges.iter().map(@protobuf.size_of).map(s => 1U + @protobuf.size_of(s) + s).fold(init=0U, UInt::op_add)
  size
}
pub impl Default for Edge with default() -> Edge {
  Edge::{
    edge_id : String::default(),
    weight : None,
    graph : None,
    source_vertex : None,
    target_vertex : None,
    parallel_edges : [],
  }
}
pub async fn[R: @protobuf.AsyncReader] Edge::read(reader : R) -> Edge raise {
  let reader = @protobuf.LimitedReader::new(reader)
  Edge::read_with_limit(reader)
}
pub async fn[R: @protobuf.AsyncReader] Edge::read_with_limit(reader : @protobuf.LimitedReader[R], limit ?: Int) -> Edge raise {
  let new_limit = if reader.limit is Some(l) && limit is Some(limit) {
    if l < limit { raise @protobuf.EndOfStream }
    Some(l - limit)
  } else { None }
  reader.limit = limit
  let msg = Edge::default()
  try {
    for {
      match (reader |> @protobuf.async_read_tag()) {
      (1, _) => msg.edge_id = reader |> @protobuf.async_read_string()
      (2, _) => msg.weight = reader |> @protobuf.async_read_double() |> Some
      (3, _) => msg.graph =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Graph::default()
    } else {
      Graph::read_with_limit(reader, limit=len)
    }
  } |> Some
      (4, _) => msg.source_vertex =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Vertex::default()
    } else {
      Vertex::read_with_limit(reader, limit=len)
    }
  } |> Some
      (5, _) => msg.target_vertex =   {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Vertex::default()
    } else {
      Vertex::read_with_limit(reader, limit=len)
    }
  } |> Some
      (6, _) => msg.parallel_edges.push(  {
    let len = reader |> @protobuf.async_read_int32()
    if len == 0 {
      Edge::default()
    } else {
      Edge::read_with_limit(reader, limit=len)
    }
  })
       (_, wire) => reader |> @protobuf.async_read_unknown(wire)
      }
    }
  } catch {
    @protobuf.EndOfStream => ()
    err => raise err
  }
  reader.limit = new_limit
  msg
}
pub async fn[W: @protobuf.AsyncWriter] Edge::write(self:Self, writer : W) -> Unit raise {
  writer |> @protobuf.async_write_varint(10UL);writer |> @protobuf.async_write_string(self.edge_id)
  match self.weight {
    Some(v) => {
      writer |> @protobuf.async_write_varint(17UL);writer |> @protobuf.async_write_double(v)
    }
    None => ()
  }
  match self.graph {
    Some(v) => {
      writer |> @protobuf.async_write_varint(26UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
  match self.source_vertex {
    Some(v) => {
      writer |> @protobuf.async_write_varint(34UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
  match self.target_vertex {
    Some(v) => {
      writer |> @protobuf.async_write_varint(42UL);writer |> @protobuf.async_write_uint32(@protobuf.size_of(v)); v.write(writer)
    }
    None => ()
  }
  for i in 0..<self.parallel_edges.length() {
        writer |> @protobuf.async_write_varint(50UL)
    writer |> @protobuf.async_write_uint32(@protobuf.size_of(self.parallel_edges[i])); self.parallel_edges[i].write(writer)
  }
}
pub impl ToJson for Edge with to_json(self) {

  let json: Map[String, Json] = {}
  if self.edge_id != Default::default() {
  json["edgeId"] = self.edge_id.to_json()
  }
  match self.weight {
      Some(v) => json["weight"] = v.to_json()
      _ => ()
    }
  match self.graph {
      Some(v) => json["graph"] = v.to_json()
      _ => ()
    }
  match self.source_vertex {
      Some(v) => json["sourceVertex"] = v.to_json()
      _ => ()
    }
  match self.target_vertex {
      Some(v) => json["targetVertex"] = v.to_json()
      _ => ()
    }
  if self.parallel_edges != Default::default() {
  json["parallelEdges"] = self.parallel_edges.to_json()
  }
  Json::object(json)
}
pub impl @json.FromJson for Edge with from_json(json: Json, path: @json.JsonPath) -> Edge raise {
  guard json is Object(obj) else {
    raise @json.JsonDecodeError((path, "Expected an object for Edge"))
  }
  let message = Edge::default()

  for key, value in obj {
    match (key, value) {
      ("edgeId", value) => message.edge_id = @json.from_json(value, path~)
      ("weight", value) => message.weight = Some(@json.from_json(value, path~))
      ("graph", value) => message.graph = Some(@json.from_json(value, path~))
      ("sourceVertex", value) => message.source_vertex = Some(@json.from_json(value, path~))
      ("targetVertex", value) => message.target_vertex = Some(@json.from_json(value, path~))
      ("parallelEdges", Array(value)) => message.parallel_edges = value.map(v => 
@json.from_json(v, path~))
      key => raise @json.JsonDecodeError((path, "Unknown field \{key}"))
      }
  }
  message
}
