///|
/// Protobuf varint wire type.
pub const WIRE_TYPE_VARINT : UInt = 0U

///|
/// Protobuf 64-bit fixed-width wire type.
pub const WIRE_TYPE_FIXED64 : UInt = 1U

///|
/// Protobuf length-delimited wire type.
pub const WIRE_TYPE_LENGTH_DELIMITED : UInt = 2U

///|
/// Protobuf start-group wire type.
pub const WIRE_TYPE_START_GROUP : UInt = 3U

///|
/// Protobuf end-group wire type.
pub const WIRE_TYPE_END_GROUP : UInt = 4U

///|
/// Protobuf 32-bit fixed-width wire type.
pub const WIRE_TYPE_FIXED32 : UInt = 5U
